### ISSUE TITLE
`wire` is already a taken name

### ISSUE THREAD

**Issue by joedborg** [snapcrafters/wire#1]
@flexiondotorg @popey @evandandrea 

Seems to be a "hello world" though.

**Comment by popey** [comment]
I've kicked off a [thread](https://forum.snapcraft.io/t/please-revoke-wire/2131) on the forum to discuss this process.

**Comment by joedborg** [comment]
Cheers @popey

**Comment by popey** [comment]
This is now fixed. I have uploaded an amd64 build to the candidate channel.
