### ISSUE TITLE
[Enhancement]: support another OS

### ISSUE THREAD

**Issue by itJunky** [snapcrafters/wire#14]
### What changes would you like?

For chatting with my friends I need a win and mac versions of application. If nobody doesn't have this client, it is not needed to me too.

**Comment by popey** [comment]
Hi. Thanks for the issue report. This repository is only for the snap store packaging for the Wire for Linux desktop application. It's not run by Wire themselves. I believe your question is either answered by, or can be researched better on the official Wire website. https://wire.com/en
